AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Lambda functions of Sobre el Video API'

Parameters:
  BaseStackName:
    Description: 'Base name of the stack set'
    Type: 'String'
    Default: 'sobre-el-video'

# NOTE: only declares Lambda functions
Resources:
  StoreVideoFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: 'store_video/'
      Handler: 'index.lambda_handler'
      Runtime: 'python3.7'
