AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template of DynamoDB table for Sobre el Video'

Parameters:
  ReadCapacityUnits:
    Description: 'Read Capacity Units (RCU) of the main table'
    Type: 'Number'
    Default: 1
  WriteCapacityUnits:
    Description: 'Write Capacity Units (WCU) of the main table'
    Type: 'Number'
    Default: 1

Resources:
  MainTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'User'
          AttributeType: 'S'
        - AttributeName: 'Date'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'User'
          KeyType: 'HASH'
        - AttributeName: 'Date'
          KeyType: 'RANGE'
      BillingMode: 'PROVISIONED'
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits

Outputs:
  MainTableName:
    Description: 'Name of the main table'
    Value: !Ref MainTable
    Export:
      Name: !Sub '${AWS::StackName}-name'
  MainTableArn:
    Description: 'ARN of the main table'
    Value: !GetAtt MainTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-arn'
