AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sobre el Video: allocates a package repository (S3 bucket) for AWS Lambda'

Resources:
  PackageRepository:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  S3BucketName:
    Description: 'Name of the created package repository for AWS Lambda'
    Value: !Ref PackageRepository
    Export:
      Name: !Sub '${AWS::StackName}-name'
  S3BucketArn:
    Description: 'ARN of the created package repository for AWS Lambda'
    Value: !GetAtt PackageRepository.Arn
    Export:
      Name: !Sub '${AWS::StackName}-arn' 
