AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template of the S3 bucket for uploaded video files'

Resources:
  VideoBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'

Outputs:
  S3BucketName:
    Description: 'Name of the S3 bucket for video files'
    Value: !Ref VideoBucket
    Export:
      Name: !Sub '${AWS::StackName}-name'
  S3BucketArn:
    Description: 'ARN of the S3 bucket for video files'
    Value: !GetAtt VideoBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-arn'
